### ISSUE TITLE
cdns aren't working

### ISSUE THREAD

**Issue by carrie-murchison** [blake-Hansen/WDF-Capstone#1]
Bootstrap js file should be:

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.5.3/js/bootstrap.min.js" integrity="sha512-8qmis31OQi6hIRgvkht0s6mCOittjMa9GMqtK9hes5iEQBQE/Ca6yGE5FsW36vyipGoWQswBj/QBm2JR086Rkw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

**Comment by blake-Hansen** [comment]
Thankyou for the help.
